### ISSUE TITLE
REST term lists aren't normalized

### ISSUE THREAD

**Issue by masterfool** [commonsense/conceptnet#12]
The wiki states that: "Every term in the term list will be normalized according to the language you specify, so for example /list/en/dogs is the same as /list/en/dog."

But that's not the case:
http://conceptnet5.media.mit.edu/data/5.2/assoc/list/en/dog
http://conceptnet5.media.mit.edu/data/5.2/assoc/list/en/dogs

The former has many results; the latter has none.

**Comment by rspeer** [comment]
Hmm, you're right. Probably the best thing for me to do at this point is to change the documentation.

**Comment by rspeer** [comment]
Also: I recognize the versions are confusing, but the ConceptNet 5 issues page is https://github.com/commonsense/conceptnet5/issues, not here. Did I accidentally leave a link to here?

**Comment by masterfool** [comment]
Should I open an issue on the version 5 site then? If it's just the documentation that is wrong, is there a REST way to normalize terms?

**Comment by rspeer** [comment]
Opening the feature request on the conceptnet5 repository would be fine, but you don't need to; I'm already looking at whether I can reasonably get the feature into 5.3. Sorry about the oversight; I guess I've been focusing too much on the Python side.

**Comment by rspeer** [comment]
It'll be in 5.3 when I manage to deploy it.
