### ISSUE TITLE
What's the detailed meaning of weight?

### ISSUE THREAD

**Issue by junyuGao** [commonsense/conceptnet#14]
In the official document, the weight field is explained as "the strength with which this edge expresses this assertion. A typical weight is 1, but weights can be higher or lower. All weights are positive."

However, I still don't know how the weights are calculated in the graph. What's the metric to evaluate the weight value for each edge? By using occurrence frequency or other machine learning techniques such as random walk?

Thank you very much!

**Comment by rspeer** [comment]
This was a ConceptNet 5 question, answered at https://github.com/commonsense/conceptnet5/issues/152 .
