### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: You haven't set the database ENGINE setting yet.

### ISSUE THREAD

**Issue by ghost** [commonsense/conceptnet#9]
I'm a beginning ConceptNet developer. I followed all the instructions and installed: newest version of Python, Django, SQLite, ConceptNet 4 together with the database ConceptNet.db. I can import conceptnet.models.\* in Python shell. The database file is stored in my home did (~/.conceptnet/ConceptNet.db - it's also set correctly in ConceptNet django config). But when I try to follow the basic example (dog = Concept.get('dog','en')) I receive the following error:

(...)
django.core.exceptions.ImproperlyConfigured: You haven't set the database ENGINE setting yet.
(...)

I've tried everything I could guess and I can't fix it... It's very annoying issue. Anyone can give me any suggestion how to fix it?

**Comment by ghost** [comment]
PS: I installed everything using setup.py files in each downloaded package. System path settings also seem to be configured fine.

**Comment by ghost** [comment]
PS2: My development environment is: MacOSX Lion

**Comment by kcarnold** [comment]
Sounds like a configuration issue. You should ask your question on the [conceptnet-users list](http://groups.google.com/group/conceptnet-users/), where it's likely that some other user can help you out.

**Comment by ghost** [comment]
I was having the same problem. I found the solution to mine on the conceptnet-users Google group: 
https://groups.google.com/forum/#!searchin/conceptnet-users/improperlyconfigured/conceptnet-users/Uu7CyHNtS9M/0-0UHbRkrdwJ

SOLUTION:

You probably have Django 1.4 as part of your installation, and ConceptNet 4 had some defaults set for Django 1.3.

You need to edit one particular settings file, as per
https://groups.google.com/forum/?fromgroups#!topic/conceptnet-users/yhbZIXMF-bQ

In your site-packages/conceptnet/django_settings you need to add to the file **init**.py the lines

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.'+DATABASE_ENGINE,
        'NAME': DATABASE_NAME,
        'USER': DATABASE_USER,
        'PASSWORD': DATABASE_PASSWORD,
        'HOST': DATABASE_HOST,
        'PORT': DATABASE_PORT,
        'OPTIONS': DATABASE_OPTIONS
    }
}

In Mac OS X distributions of Python 2.7, you'll find that buried under:

 /Library/frameworks/Python.framework/versions/2.7/lib/python-2.7/
